### ISSUE TITLE
Definir funcionalidades

### ISSUE THREAD

**Issue by agarzon48** [agarzon48/mentory-revisions#2]
Necesitamos definir las funcionalidades de la aplicación.

La idea es que nos sirva para facilitar el trabajo de revisión conforme a las siguientes bases:

* Todos los estudiantes entregan sus proyectos en repositorios de github, de modo que debemos soportar una funcionalidad que permita subir el enlace (opcionalmente, que notifique a los compañeros o potenciales revisores).
* Profesores y T.A. deben poder revisar el trabajo e insertar sus valoraciones en github issues. Podemos empezar trabajando a mano y luego estudiar integrarlo con github/la academia para automatizar y que solo debamos revisar en un sitio.
* Otros estudiantes deben poder valorar el trabajo de sus compañeros y compañeras, de tal modo que antes de aceptarse o rechazarse un trabajo, cuente con los comentarios y valoración de profesor, T.A. y al menos dos estudiantes (**este es el núcleo de la aplicación**).

**Fecha límite:**
15/05/2023

**Condiciones de satisfacción:**

- [x] Establecidas funcionalidades de la aplicación
- [x] Creadas historias de usuario y tareas para empezar a trabajar

---

## MVP

Un MVP sería una hoja de datos (excel) que cuadrara eje de trabajo revisado VS. eje de estudiantes. Se requiere que dos estudiantes hayan revisado un trabajo para entrar a valoración del equipo docente. Se requiere que el estudiante haya revisado al menos dos trabajos para entrar a valoración del equipo docente.

A partir de esta idea, sería dar con una interfaz agradable (no tiene por qué ser una hoja de datos, utilicemos preferiblemente tarjetas, listas u otros elementos más amigables). La lógica de negocio puede ir cambiando, porque estamos probando este sistema de evaluación.

### FUNCIONALIDADES BÁSICAS

* La app cuenta con una base de datos que incluye todos los projects de la academia
* El equipo docente puede crear un grupo, compuesto por una cohorte de estudiantes
* Creado el grupo, la app genera una visualización que incluye:
  * Lista de projects
  * Estado del proyecto (por entregar, entregado, revisable -revisado por dos estudiantes-, aprobado, rechazado, nº de revisores, sentido del voto de cada revisor -aprobado o rechazado-, enlaces al repo y a los comentarios de cada revisor) 
* El equipo docente puede visualizar, editar y eliminar los grupos en los que consta como responsable
* Los estudiantes pueden visualizar el grupo en que constan como inscritos
* Los estudiantes pueden valorar trabajos de sus compañeros y compañeras

**Comment by AlvaroMartinFernandez** [comment]
Yo me propongo para hacer el login que estoy realizando uno con node y mysql, en mondo db no tiene que cambiar demasiado

**Comment by agarzon48** [comment]
Cerrado documento de funcionalidades
[https://docs.google.com/document/d/19VrE5HiHRirlbf7HlB_gcJ8dwP1VQxp16fsqzng4f7A/edit?usp=sharing](https://docs.google.com/document/d/19VrE5HiHRirlbf7HlB_gcJ8dwP1VQxp16fsqzng4f7A/edit?usp=sharing)
