### ISSUE TITLE
[DISEÑO] Adaptar diseño de la página de login

### ISSUE THREAD

**Issue by agarzon48** [agarzon48/mentory-revisions#3]
Vamos a empezar con un MVP. Como todos los estudiantes, mentores y profesores tenemos cuenta en github, gestionaremos el inicio de sesión por medio de su sistema.

## Descripción de la tarea

Es necesario adaptar el diseño de la página de login para que incluya tan solo la opción de iniciar sesión con github

**Diseño:** [https://www.figma.com/file/IxOMcv2z7GnkmaUs48tIup/Untitled?type=design&node-id=17-46](https://www.figma.com/file/IxOMcv2z7GnkmaUs48tIup/Untitled?type=design&node-id=17-46)

**Condiciones de satisfacción:**

- [x] El diseño de la página de login no muestra la opción de crear cuenta
- [x] El diseño de la página de login no muestra la opción de introducir email/contraseña
- [x] El diseño de la página de login muestra la opción de iniciar sesión con github

**Comment by danilopgon** [comment]
El diseño está actualizado para mostrar, únicamente, un botón de login con Github (con su logo) que lleva a su página de autenticación:

![image](https://github.com/agarzon48/mentory-revisions/assets/113547781/ed384546-da6d-4ddd-a251-f31fa195d9f5)

**Comment by agarzon48** [comment]
Perfect! Cierro issue
