### ISSUE TITLE
[ADMIN VIEW - DASHBOARD] Diseñar vista principal del administrador

### ISSUE THREAD

**Issue by agarzon48** [agarzon48/mentory-revisions#5]
## Descripción de la tarea

Partiendo del diseño existente:

* No es necesario que aparezca la fecha de inicio. En caso de querer conservarla, lo óptimo sería incluir también la fecha de finalización
* Hay que preparar una visualización del desplegable de las cards de cada curso. En ella, debería aparecer una línea por cada estudiante. En cada línea de estudiante debe visualizarse:
    * El nombre del estudiante
    * Tres marcas (círculo o similar) por cada tarea del curso. Estas tendrán un código de color para poder identificar de un vistazo los diferentes estados de la tarea.
        * La primera marca refiere al estado de la tarea, pudiendo estar en tres estados:
            * ENTREGADO
            * APROBADO
            * RECHAZADO
        * La segunda marca refiere a las revisiones del equipo docente, pudiendo estar en tres estados:
            * REVISADA POR TA
            * REVISADA POR PROFESOR
            * REVISADA POR AMBOS
        * La tercera marca refiere a las revisiones del alumnado, pudiendo estar en dos estados:
            * REVISADA
            * NO REVISADA

**Diseño:** [https://www.figma.com/file/IxOMcv2z7GnkmaUs48tIup/Untitled?type=design&node-id=17-46](https://www.figma.com/file/IxOMcv2z7GnkmaUs48tIup/Untitled?type=design&node-id=17-46)

**Condiciones de satisfacción:**

- [x] O bien no aparece la fecha del curso o bien aparece también la fecha final
- [x] En el diseño aparece al menos una de las cards desplegadas
- [x] La card desplegada muestra varias filas, una por alumno
- [x] En cada fila, aparece en primer lugar el nombre del alumno
- [x] A continuación del nombre del alumno disponemos de una leyenda visual con los estados de la tarea (el nombre de la tarea debería verse en un tooltip o similar para no ensuciar la interfaz
- [x] Disponemos de un código de color para cada estado (pueden repetirse entre criterios -estado de la tarea, revisión docente, revisión de alumnos- pero no dentro de cada criterio -revisada vs. no revisada, etc.-).

**Comment by danilopgon** [comment]
Cambios aplicados. No sé si estoy muy seguro del tema iconos pero, ¿a lo mejor con varios círculos de color sería más lioso?

![image](https://github.com/agarzon48/mentory-revisions/assets/113547781/f9f77b20-8df7-4545-8d7e-db36e9cc20ff)

**Comment by danilopgon** [comment]
Elimino los emails también de esta vista

**Comment by agarzon48** [comment]
Creo que así es perfecto. Justo pensé en el tema iconos, pero no lo quise anotar por no dirigir mucho las decisiones que tomaras. Cierro issue.
