### ISSUE TITLE
[ADMIN VIEW - ADD GROUP] Diseñar vista de creación de grupo

### ISSUE THREAD

**Issue by agarzon48** [agarzon48/mentory-revisions#6]
## Descripción de la tarea

Partiendo del diseño existente:

* No es necesario que aparezca la fecha de inicio. En caso de querer conservarla, lo óptimo sería incluir también la fecha de finalización
* No es necesario que aparezca el email del estudiante
* Debemos disponer de una opción para editar la línea del estudiante, similar a la opción de eliminación implementada en el diseño (incluir visualización del estado de edición)

**Diseño:** [https://www.figma.com/file/IxOMcv2z7GnkmaUs48tIup/Untitled?type=design&node-id=17-46](https://www.figma.com/file/IxOMcv2z7GnkmaUs48tIup/Untitled?type=design&node-id=17-46)

**Condiciones de satisfacción:**

- [x] O bien no aparece la fecha del curso o bien aparece también la fecha final
- [x] No aparece el email del estudiante
- [x] Junto al botón de eliminación de fila, hay otro de edición
- [x] Se muestra un ejemplo de la vista de edición (puede ser un modal, una página aparte o simplemente que los campos de la fila pasen a ser inputs, libertad en este sentido)

**Comment by danilopgon** [comment]
He tirado por un modal para la edición, bastante similar al que hay para añadir tarea en la vista de student:



![Image](https://github.com/agarzon48/mentory-revisions/assets/113547781/80045f8a-c724-43f8-8f5f-d73e14ed1914)

**Comment by agarzon48** [comment]
Perfect, vamos con ello!
