### ISSUE TITLE
[ADMIN VIEW - ADD TASK] Diseñar interfaz para añadir tareas

### ISSUE THREAD

**Issue by agarzon48** [agarzon48/mentory-revisions#7]
## Descripción de la tarea

Necesitamos una interfaz para añadir tareas al grupo. No hay diseño actualmente, sugiero incluirlo en la vista de ADD GROUP, pero podría ser mediante cualquier otro sistema

* Necesitamos poder añadir tareas al grupo, partiendo de una lista predefinida y pudiendo incluir nuevas tareas que no estén en la lista predefinida (Select con opción de añadir nuevos datos?)
* Necesitamos un listado de tareas, como el de estudiantes que hay ahora en el diseño, que nos permita editarlas y eliminarlas

**Diseño:** [https://www.figma.com/file/IxOMcv2z7GnkmaUs48tIup/Untitled?type=design&node-id=17-46](https://www.figma.com/file/IxOMcv2z7GnkmaUs48tIup/Untitled?type=design&node-id=17-46)

**Condiciones de satisfacción:**

- [x] Disponemos de una interfaz para añadir tareas
- [x] Las tareas a añadir pueden estar en una lista o pueden añadirse ad hoc
- [x] Añadidas las tareas, las podemos visualizar en una lista
- [x] Podemos editar las tareas de la lista
- [x] Podemos eliminar las tareas de la lista

**Comment by danilopgon** [comment]
¿Sería separar los inputs de este modo para poder utilizar las ya escritas previamente y las nuevas?

![image](https://github.com/agarzon48/mentory-revisions/assets/113547781/6069cf24-377c-4b3e-a94a-bee1a8bf9785)

**Comment by agarzon48** [comment]
A mí me parece perfect. Cierro issue
